swagger: "2.0"
info:
  title: "Insights Host Inventory"
  version: "0.1"
basePath: /api
paths:
  /hello:
    get:
      responses:
        default:
          description: A sole route that print a greeting.
